### ISSUE TITLE
it's not allowed to use the .length function, because it maybe use iteration

### ISSUE THREAD

**Issue by Devil123166** [Paeti/kmps#2]
https://github.com/Paeti/kmps/blob/fb61c6dac9164cbf1a7a13839acde523ffe49349/src/main/scala/praktikum_3.scala#L23

**Comment by Paeti** [comment]
it's not the list.lenght. it's the tracks attribute lenght

**Comment by Devil123166** [comment]
K. you can close that issue now. I'm sorry for that mistake
